# Script to make season.obic table
# Table is based on Tabel 2 in Huinink (2018) and links to crops.obic$crop_season
# Not all landuses in the original table appear in brp and some of the brp crops have been assigned to "overig" and could be reclassified later.
library(data.table)
season.obic <- data.frame(landuse = c('naaldbos', 'loofbos', 'groot fruit', 'klein fruit',
                                      'aardappelen', 'pootaardappelen', 'fabrieksaardappelen',
                                      'suikerbieten', 'wintertarwe', 'zomergerst', 'snijmais',
                                      'laanbomen_onderstammen', 'overige boomteelt', 'graszaad', 'asperge',
                                      'schorseneren', 'prei, spruiten, koolsoorten', 'erwten, bonen',
                                      'witlof, selderij, uien', 'was bospeen', 'tulpen, narcis, hyacint',
                                      'dahlia', 'bladgroenten', 'beweid gemaaid gras',
                                      'plantsoenen', 'gazons', 'kampeerterreinen, ligweiden', 'sportvelden',
                                      'overig'),
                          req_days_pre_glg = c(170, 170, 170, 170,
                                               155, 150, 155,
                                               155, 165, 165, 130,
                                               170, 170, 170, 170,
                                               170, 100, 135,
                                               75,  100, 180,
                                               100, 100, 180,
                                               180, 100, 100, 100,
                                               0),
                          req_days_post_glg =c(75, 75, 75, 75,
                                               35,  0, 65, 
                                               75, 10,  0, 35,
                                               75, 55, 15, 75,
                                               75,125,-15,
                                               65, 25,140,
                                              140, 75, 75,
                                               75, 75, 45, 75,
                                               0),
                          total_days = c(245, 245, 245, 245,
                                         190, 150, 220,
                                         230, 175, 170, 165,
                                         245, 225, 185, 245,
                                         245, 225, 130,
                                         140, 125, 320,
                                         320, 175, 225,
                                         225, 210, 145, 255,
                                         0))
save(season.obic,file = 'data/season.obic.RData')
