# Script to modify crops.obic
library(data.table)
library(dplyr)

cr <- read.csv('DEV/crops_obic.csv') %>% setDT()

# Add scientific name of crop scecies
cr[grepl('ardappel', cr$crop_name),crop_name_scientific:= 'solanum tuberosum']
cr[grepl('uinbouwzaden|Bloemzaden open|kwekerijgewassen \\(inclusief bloemzaden\\)|^Bloembollen en - knollen$|Fruit|oomkwekerij|Rand', cr$crop_name),crop_name_scientific:= 'overig']
cr[grepl('Tarwe|tarwe', cr$crop_name),crop_name_scientific:= 'triticum aestivum']
cr[grepl('Gerst|gerst', cr$crop_name),crop_name_scientific:= 'horderum vulgare']
cr[grepl('Rogge|rogge', cr$crop_name),crop_name_scientific:= 'secale cereale']
cr[grepl('Haver|haver', cr$crop_name),crop_name_scientific:= 'avena sativa']
cr[grepl('erwten|Erwten|Schokkers', cr$crop_name),crop_name_scientific:= 'pisum sativum']
cr[grepl('Bonen|bonen', cr$crop_name),crop_name_scientific:= 'phaseolus vulgaris']
cr[grepl('Pronkbonen', cr$crop_name),crop_name_scientific:= 'phaseolus coccineus'] #overwrites bonen for pronkbonen
cr[grepl('Sojabonen', cr$crop_name),crop_name_scientific:= 'glycine max'] #overwrite bonen for sojabonen
cr[grepl('Karwij|karwij|kummel', cr$crop_name),crop_name_scientific:= 'carum carvi']
cr[grepl('maanzaad', cr$crop_name),crop_name_scientific:= 'papaver somniferum']
cr[grepl('Vlas', cr$crop_name),crop_name_scientific:= 'linum usitatissimum']
cr[grepl('Bieten|bieten', cr$crop_name),crop_name_scientific:= 'beta vulgaris']
cr[grepl('Luzerne', cr$crop_name),crop_name_scientific:= 'medicago sativa']
cr[grepl('Mais|mais', cr$crop_name),crop_name_scientific:= 'zea mays']
cr[grepl('Uien|uien|ierui', cr$crop_name),crop_name_scientific:= 'allium cepa']
cr[grepl('Grasland|grasland|^Graszaad$|blijvend gras$|Graszaad, overig|tijdelijk gras$|raszoden|Graszaad \\(inclusief', cr$crop_name),crop_name_scientific:= 'gras overig']
cr[grepl('Engels raai', cr$crop_name),crop_name_scientific:= 'lolium perenne']
cr[grepl('Italiaans raai|esterwolds|, Italiaans', cr$crop_name),crop_name_scientific:= 'lolium multiflorum']
cr[grepl('Sorghum|sorgho', cr$crop_name),crop_name_scientific:= 'sorghum bicolor']
cr[grepl('Rietzwenk|rietzwenk', cr$crop_name),crop_name_scientific:= 'Festuca arundinacea']
cr[grepl('Miscanthus', cr$crop_name),crop_name_scientific:= 'miscanthus']
cr[grepl('Roodzwenk|roodzwenk', cr$crop_name),crop_name_scientific:= 'festuca rubra']
cr[grepl('eldbeemdgras|veldbeemd', cr$crop_name),crop_name_scientific:= 'poa pratensis']
cr[grepl('Triticale', cr$crop_name),crop_name_scientific:= 'triticale']
cr[grepl('atuur|ufferstrook|Sloot|Overige', cr$crop_name)&is.na(crop_name_scientific),crop_name_scientific:= 'overig']
cr[grepl('argetes|frikaantje', cr$crop_name),crop_name_scientific:= 'targetes']
cr[grepl('Hop', cr$crop_name),crop_name_scientific:= 'humulus lupus']
cr[grepl('Teff', cr$crop_name),crop_name_scientific:= 'eragrostis tef']
cr[grepl('Spelt', cr$crop_name),crop_name_scientific:= 'triticum spelta']
cr[grepl('Gele mosterd', cr$crop_name),crop_name_scientific:= 'sinapis alba']
cr[grepl('Zwarte mos', cr$crop_name),crop_name_scientific:= 'brassica nigra']
cr[grepl('Ethiopische mos', cr$crop_name),crop_name_scientific:= 'brassica carinata']
cr[grepl('Sarepta mosterd', cr$crop_name),crop_name_scientific:= 'brassica juncea']
cr[grepl('Cichorei|lof', cr$crop_name),crop_name_scientific:= 'chichorium intybus']
cr[grepl('ndijvie', cr$crop_name),crop_name_scientific:= 'chichorium endivia']
cr[grepl('anariezaad', cr$crop_name),crop_name_scientific:= 'phalaris canariensis']
cr[grepl('onnebloem', cr$crop_name),crop_name_scientific:= 'helianthus anuus']
cr[grepl('Saffloer', cr$crop_name),crop_name_scientific:= 'carthamus tinctorius']
cr[grepl('Meekrap', cr$crop_name),crop_name_scientific:= 'rubia tinctorum']
cr[grepl('Teunisbloem', cr$crop_name),crop_name_scientific:= 'oenothera']
cr[grepl('Brandnetel', cr$crop_name),crop_name_scientific:= 'Urtica urens']
cr[grepl('Boekweit', cr$crop_name),crop_name_scientific:= 'fagopyrum esculentum']
cr[grepl('Gierst', cr$crop_name),crop_name_scientific:= 'panicum miliaceum']
cr[grepl('Bos|Lijnzaad|oenten|bomen|ilgen|Klaverzaad', cr$crop_name),crop_name_scientific:= 'overig']
cr[grepl('peen', cr$crop_name),crop_name_scientific:= 'daucus carota'] # overwrites bos for bospeen
cr[grepl('Lupinen', cr$crop_name),crop_name_scientific:= 'lupinus']
cr[grepl('aapzaad', cr$crop_name),crop_name_scientific:= 'brassica rapa']
cr[grepl('Zwaardherik', cr$crop_name),crop_name_scientific:= 'Eruca sativa']
cr[grepl('Raketblad', cr$crop_name),crop_name_scientific:= 'solanum sisymbriifolium']
cr[grepl('Klaver, rode', cr$crop_name),crop_name_scientific:= 'trifolium pratense']
cr[grepl('Klaver, witte', cr$crop_name),crop_name_scientific:= 'trifolium repens']
cr[grepl('olklaver', cr$crop_name),crop_name_scientific:= 'lotus']
cr[grepl('Esparcette', cr$crop_name),crop_name_scientific:= 'onobrychis viciifolia']
cr[grepl('Wikke, voeder', cr$crop_name),crop_name_scientific:= 'vicia sativa']
cr[grepl('Wikke, bonte', cr$crop_name),crop_name_scientific:= 'vicia villosa']
cr[grepl('ennep', cr$crop_name),crop_name_scientific:= 'cannabis sativa']
cr[grepl('ahlia', cr$crop_name),crop_name_scientific:= 'dahlia']
cr[grepl('ladiool', cr$crop_name),crop_name_scientific:= 'gladiolus communis']
cr[grepl('Hyacint', cr$crop_name),crop_name_scientific:= 'hyacinthus orientalis']
cr[grepl('Kuifhyacint', cr$crop_name),crop_name_scientific:= 'leopoldia comosa']
cr[grepl('Iris|iris', cr$crop_name),crop_name_scientific:= 'iris germanica']
cr[grepl('rokus', cr$crop_name),crop_name_scientific:= 'crocus']
cr[grepl('Lelie', cr$crop_name),crop_name_scientific:= 'lilium']
cr[grepl('arcis', cr$crop_name),crop_name_scientific:= 'narcissus']
cr[grepl('Tulp|tulp', cr$crop_name),crop_name_scientific:= 'tulipa']
cr[grepl('antedeschia', cr$crop_name),crop_name_scientific:= 'zantedeschia aethiopica']
cr[grepl('maryllis', cr$crop_name),crop_name_scientific:= 'amaryllis belladonna']
cr[grepl('lauw druifje', cr$crop_name),crop_name_scientific:= 'muscari botryoides']
cr[grepl('aleriaan', cr$crop_name),crop_name_scientific:= 'valeriana officinalis']
cr[grepl('Knoflook', cr$crop_name),crop_name_scientific:= 'allium sativum']
cr[grepl('Quinoa', cr$crop_name),crop_name_scientific:= 'chenopodium quinoa']
cr[grepl('Pastinaak', cr$crop_name),crop_name_scientific:= 'pastinaca sativa']
cr[grepl('Pioenroos', cr$crop_name),crop_name_scientific:= 'paeonia']
cr[grepl('Lavas', cr$crop_name),crop_name_scientific:= 'levisticum officinale']
cr[grepl('Oregano', cr$crop_name),crop_name_scientific:= 'Origanum vulgare']
cr[grepl('Goudsbloem', cr$crop_name),crop_name_scientific:= 'calendula officinalis']
cr[grepl('', cr$crop_name),crop_name_scientific:= '']

head(cr[is.na(crop_name_scientific),crop_name],1)

unique(cr[crop_name_scientific == 'carum carvi',.(crop_name, crop_name_scientific)])
cr[grepl('noflook', cr$crop_name), .(crop_name, crop_name_scientific)]
cr[grepl('Engels|engels', cr$crop_name), .(crop_name, crop_name_scientific)]
